// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDb1clrvC_7_UWt0H7hnMdRxidx72ZZeaM',
    appId: '1:676154272146:web:8ccef9f6d520c4c9b9b94b',
    messagingSenderId: '676154272146',
    projectId: 'traveler-8b589',
    authDomain: 'traveler-8b589.firebaseapp.com',
    storageBucket: 'traveler-8b589.appspot.com',
    measurementId: 'G-R56L25M4J6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDWr9iGw4gSbJmEpvVYCO1gaQxOXmJb-54',
    appId: '1:676154272146:android:1a8d59ff607f64f8b9b94b',
    messagingSenderId: '676154272146',
    projectId: 'traveler-8b589',
    storageBucket: 'traveler-8b589.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDar1efDVZ_XRyz_P9UUj-eQAj9VHkpR_o',
    appId: '1:676154272146:ios:acde439230349c8ab9b94b',
    messagingSenderId: '676154272146',
    projectId: 'traveler-8b589',
    storageBucket: 'traveler-8b589.appspot.com',
    iosClientId: '676154272146-1spbjui60gu517kshddb5crp9obj7ti4.apps.googleusercontent.com',
    iosBundleId: 'com.example.traveler',
  );
}
